<?php
/**
 * Seed REAL Algerian restaurants for 9 new cities
 * Cities: Constantine, Annaba, Setif, Bejaia, Tlemcen, Tizi Ouzou, Biskra, Ghardaia, Tipaza
 *
 * Data sourced from TripAdvisor, Google Maps, Petit Fute, RestoAlgerie, Mapcarta, OpenStreetMap
 * Run: php database/seed_restaurants_cities.php
 */

$pdo = new PDO('mysql:host=127.0.0.1;dbname=lebonresto;charset=utf8mb4', 'root', '', [
    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    PDO::ATTR_EMULATE_PREPARES => false,
]);

function slugify($text) {
    $text = iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $text);
    $text = strtolower($text);
    $text = preg_replace('/[^a-z0-9]+/', '-', $text);
    return trim($text, '-');
}


$restaurants = [

    // =========================================================================
    // CONSTANTINE (Wilaya 25)
    // =========================================================================
    [
        'nom' => 'Qasar Restaurant',
        'ville' => 'Constantine',
        'wilaya' => 'Constantine',
        'adresse' => 'Oued Rhumel Street, Cités des Arcades Romaines, Constantine 25000',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 36.3536,
        'gps_longitude' => 6.6145,
        'phone' => '+213 31 64 00 00',
        'note_moyenne' => 4.20,
        'price_range' => '$$$',
        'description' => 'Restaurant du Marriott proposant un buffet méditerranéen avec des saveurs libanaises, italiennes et algériennes. Poissons et viandes grillés sur commande.',
    ],
    [
        'nom' => 'Restaurant Igherssan',
        'ville' => 'Constantine',
        'wilaya' => 'Constantine',
        'adresse' => '58 Rue Larbi Ben M\'hidi, Constantine 25000',
        'type_cuisine' => 'Traditionnel',
        'gps_latitude' => 36.3650,
        'gps_longitude' => 6.6147,
        'phone' => '+213 560 906 580',
        'note_moyenne' => 4.50,
        'price_range' => '$$',
        'description' => 'Restaurant traditionnel algérien offrant une vue spectaculaire sur les ponts et les gorges du Rhummel. Cuisine authentique constantinoise.',
    ],
    [
        'nom' => 'Piano Piano Food',
        'ville' => 'Constantine',
        'wilaya' => 'Constantine',
        'adresse' => 'Sidi Mabrouk, Constantine 25000',
        'type_cuisine' => 'Italien',
        'gps_latitude' => 36.3657,
        'gps_longitude' => 6.6369,
        'phone' => '+213 770 720 000',
        'note_moyenne' => 4.30,
        'price_range' => '$$',
        'description' => 'Restaurant italien et café à Sidi Mabrouk. Cuisine raffinée avec pâtes, pizzas et plats méditerranéens dans une ambiance conviviale.',
    ],
    [
        'nom' => 'Le Grand Bleu',
        'ville' => 'Constantine',
        'wilaya' => 'Constantine',
        'adresse' => '13 Lots Ain El Bey, Nouvelle Ville Ali Mendjeli, Constantine 25000',
        'type_cuisine' => 'Poissons/Fruits de mer',
        'gps_latitude' => 36.2465,
        'gps_longitude' => 6.5739,
        'phone' => '0770 37 99 53',
        'note_moyenne' => 4.10,
        'price_range' => '$$',
        'description' => 'Restaurant de poissons et fruits de mer à la Nouvelle Ville. Produits frais du jour et plats méditerranéens dans un cadre moderne.',
    ],
    [
        'nom' => 'La Boule de Neige',
        'ville' => 'Constantine',
        'wilaya' => 'Constantine',
        'adresse' => 'Centre-ville, Constantine 25000',
        'type_cuisine' => 'Pizzeria',
        'gps_latitude' => 36.3651,
        'gps_longitude' => 6.6126,
        'phone' => '+213 31 88 50 50',
        'note_moyenne' => 4.00,
        'price_range' => '$',
        'description' => 'Destination pizza incontournable de Constantine. Pizzas cuites au feu de bois, pâtisseries et glaces maison appréciées des locaux.',
    ],
    [
        'nom' => 'La Concorde',
        'ville' => 'Constantine',
        'wilaya' => 'Constantine',
        'adresse' => 'Rue Belouizdad, Constantine 25000',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 36.3625,
        'gps_longitude' => 6.6180,
        'phone' => '+213 31 92 34 56',
        'note_moyenne' => 4.20,
        'price_range' => '$$',
        'description' => 'Restaurant algérien authentique où la tradition rencontre l\'excellence culinaire. Spécialités constantinoises et couscous préparés avec soin.',
    ],
    [
        'nom' => 'Tin Box',
        'ville' => 'Constantine',
        'wilaya' => 'Constantine',
        'adresse' => 'El Khroub, Constantine 25100',
        'type_cuisine' => 'Fast food',
        'gps_latitude' => 36.2636,
        'gps_longitude' => 6.6967,
        'phone' => '+213 770 40 70 72',
        'note_moyenne' => 4.00,
        'price_range' => '$',
        'description' => 'Restaurant tendance à El Khroub proposant burgers, tacos et plats fusion. Ambiance jeune et moderne, service rapide.',
    ],
    [
        'nom' => 'Mam\'s Pizza',
        'ville' => 'Constantine',
        'wilaya' => 'Constantine',
        'adresse' => 'Rue Emir Abdelkader, El Khroub, Constantine 25100',
        'type_cuisine' => 'Pizzeria',
        'gps_latitude' => 36.2650,
        'gps_longitude' => 6.6981,
        'phone' => '+213 770 407 072',
        'note_moyenne' => 3.90,
        'price_range' => '$',
        'description' => 'Pizzeria populaire à El Khroub avec un large choix de pizzas artisanales et des plats italiens copieux.',
    ],
    [
        'nom' => 'Arabica Café Resto',
        'ville' => 'Constantine',
        'wilaya' => 'Constantine',
        'adresse' => 'Cité du 5 Juillet 1962, Constantine 25000',
        'type_cuisine' => 'Café-Restaurant',
        'gps_latitude' => 36.3478,
        'gps_longitude' => 6.5930,
        'phone' => '+213 556 78 90 12',
        'note_moyenne' => 3.80,
        'price_range' => '$',
        'description' => 'Café-restaurant moderne proposant petit-déjeuner, brunch et plats légers dans un cadre décontracté à Constantine.',
    ],
    [
        'nom' => 'APEX Restaurant et Café',
        'ville' => 'Constantine',
        'wilaya' => 'Constantine',
        'adresse' => 'El Khroub, Constantine 25100',
        'type_cuisine' => 'Café-Restaurant',
        'gps_latitude' => 36.2617,
        'gps_longitude' => 6.6941,
        'phone' => '+213 770 55 66 77',
        'note_moyenne' => 4.00,
        'price_range' => '$$',
        'description' => 'Restaurant et café moderne à El Khroub offrant une cuisine variée, des pâtisseries maison et une ambiance chaleureuse.',
    ],

    // =========================================================================
    // ANNABA (Wilaya 23)
    // =========================================================================
    [
        'nom' => 'Le Baroque Restaurant & Lounge',
        'ville' => 'Annaba',
        'wilaya' => 'Annaba',
        'adresse' => 'La Corniche, Annaba 23000',
        'type_cuisine' => 'Italien',
        'gps_latitude' => 36.9049,
        'gps_longitude' => 7.7662,
        'phone' => '+213 550 23 45 67',
        'note_moyenne' => 4.90,
        'price_range' => '$$$',
        'description' => 'Restaurant italien et méditerranéen classé n°1 à Annaba. Ambiance lounge élégante sur la corniche avec vue sur la mer.',
    ],
    [
        'nom' => 'La Renaissance',
        'ville' => 'Annaba',
        'wilaya' => 'Annaba',
        'adresse' => 'Route du Cap de Garde, Annaba 23000',
        'type_cuisine' => 'Poissons/Fruits de mer',
        'gps_latitude' => 36.9221,
        'gps_longitude' => 7.7701,
        'phone' => '+213 38 86 40 00',
        'note_moyenne' => 4.30,
        'price_range' => '$$$',
        'description' => 'Restaurant méditerranéen avec poissons frais et fruits de mer grillés. Terrasse avec vue magnifique sur la mer.',
    ],
    [
        'nom' => 'Le Jasmin',
        'ville' => 'Annaba',
        'wilaya' => 'Annaba',
        'adresse' => 'Boulevard Fellah Rachid, Annaba 23000',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 36.9003,
        'gps_longitude' => 7.7590,
        'phone' => '+213 38 45 67 89',
        'note_moyenne' => 5.00,
        'price_range' => '$$',
        'description' => 'Cuisine algérienne traditionnelle dans une ambiance familiale chaleureuse. Couscous, tajines et spécialités annabies.',
    ],
    [
        'nom' => 'Le Castanea',
        'ville' => 'Annaba',
        'wilaya' => 'Annaba',
        'adresse' => '33 Rue des Bungalows, Seraïdi, Annaba 23000',
        'type_cuisine' => 'Traditionnel',
        'gps_latitude' => 36.9184,
        'gps_longitude' => 7.6744,
        'phone' => '0676 17 31 07',
        'note_moyenne' => 4.90,
        'price_range' => '$$',
        'description' => 'Restaurant niché dans les hauteurs de Seraïdi. Cuisine traditionnelle avec des produits frais de la montagne et une vue imprenable.',
    ],
    [
        'nom' => 'Hôtel Sabri - Restaurant Belle Vue',
        'ville' => 'Annaba',
        'wilaya' => 'Annaba',
        'adresse' => 'Route du Cap de Garde, Plage Refes Zahouane, Annaba 23000',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 36.9331,
        'gps_longitude' => 7.7750,
        'phone' => '+213 560 954 742',
        'note_moyenne' => 4.00,
        'price_range' => '$$$',
        'description' => 'Restaurant d\'hôtel proposant une cuisine locale et internationale avec vue panoramique sur la baie d\'Annaba.',
    ],
    [
        'nom' => 'El Rio',
        'ville' => 'Annaba',
        'wilaya' => 'Annaba',
        'adresse' => '86 Avenue Colonel Amirouche, Annaba 23000',
        'type_cuisine' => 'Fast food',
        'gps_latitude' => 36.8980,
        'gps_longitude' => 7.7560,
        'phone' => '0674 55 28 90',
        'note_moyenne' => 3.90,
        'price_range' => '$',
        'description' => 'Fast food moderne au centre d\'Annaba. Burgers, tacos, sandwiches et boissons fraîches dans un cadre jeune et dynamique.',
    ],
    [
        'nom' => 'Lala Torkia Restaurant',
        'ville' => 'Annaba',
        'wilaya' => 'Annaba',
        'adresse' => 'Avenue 1er Novembre 1956, Annaba 23000',
        'type_cuisine' => 'Traditionnel',
        'gps_latitude' => 36.8993,
        'gps_longitude' => 7.7563,
        'phone' => '+213 38 86 12 34',
        'note_moyenne' => 4.10,
        'price_range' => '$$',
        'description' => 'Restaurant traditionnel annabi servant des plats authentiques de la cuisine de l\'Est algérien dans un cadre familial.',
    ],
    [
        'nom' => 'Le Jardin de Mer',
        'ville' => 'Annaba',
        'wilaya' => 'Annaba',
        'adresse' => 'Rue Daoudi Bachir, Annaba 23000',
        'type_cuisine' => 'Poissons/Fruits de mer',
        'gps_latitude' => 36.9075,
        'gps_longitude' => 7.7653,
        'phone' => '+213 38 86 56 78',
        'note_moyenne' => 4.20,
        'price_range' => '$$',
        'description' => 'Poissons et fruits de mer frais du jour, grillés au charbon de bois. Ambiance bord de mer agréable.',
    ],
    [
        'nom' => 'Lebanon Restaurant',
        'ville' => 'Annaba',
        'wilaya' => 'Annaba',
        'adresse' => 'Avenue Maatar Lakhdar, Annaba 23000',
        'type_cuisine' => 'Turc',
        'gps_latitude' => 36.9007,
        'gps_longitude' => 7.7540,
        'phone' => '+213 38 45 23 56',
        'note_moyenne' => 4.00,
        'price_range' => '$$',
        'description' => 'Cuisine libanaise et orientale avec mezze, grillades, shawarma et pâtisseries du Moyen-Orient.',
    ],
    [
        'nom' => 'Al-Caravelle',
        'ville' => 'Annaba',
        'wilaya' => 'Annaba',
        'adresse' => 'Rue des Frères Soudane, Annaba 23000',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 36.8998,
        'gps_longitude' => 7.7585,
        'phone' => '+213 38 45 49 86',
        'note_moyenne' => 3.80,
        'price_range' => '$$',
        'description' => 'Restaurant familial au centre d\'Annaba avec cuisine algérienne traditionnelle. Ouvert tôt le matin pour petit-déjeuner.',
    ],

    // =========================================================================
    // SETIF (Wilaya 19)
    // =========================================================================
    [
        'nom' => 'Restaurant Khaima',
        'ville' => 'Sétif',
        'wilaya' => 'Sétif',
        'adresse' => 'Entre l\'hôpital et Cité Gasria, Sétif 19000',
        'type_cuisine' => 'Traditionnel',
        'gps_latitude' => 36.1898,
        'gps_longitude' => 5.4108,
        'phone' => '+213 36 544 242',
        'note_moyenne' => 4.40,
        'price_range' => '$$',
        'description' => 'Spécialiste de la Chekhchoukha et des plats traditionnels sétifiens. Cadre typique avec décor de tente berbère.',
    ],
    [
        'nom' => 'Pizza Pino Sétif',
        'ville' => 'Sétif',
        'wilaya' => 'Sétif',
        'adresse' => 'Rue Ben Chikh Mohamed, Cité Dallas, Sétif 19000',
        'type_cuisine' => 'Pizzeria',
        'gps_latitude' => 36.1912,
        'gps_longitude' => 5.4070,
        'phone' => '0557 90 24 33',
        'note_moyenne' => 4.20,
        'price_range' => '$',
        'description' => 'Pizzeria réputée à Sétif pour ses vraies pizzas artisanales cuites au four à bois. Fortement recommandée par les locaux.',
    ],
    [
        'nom' => 'Maharaja',
        'ville' => 'Sétif',
        'wilaya' => 'Sétif',
        'adresse' => 'Park Mall, Rue Ahmed Daamouche, Sétif 19000',
        'type_cuisine' => 'Asiatique',
        'gps_latitude' => 36.1940,
        'gps_longitude' => 5.4142,
        'phone' => '+213 36 54 78 90',
        'note_moyenne' => 4.10,
        'price_range' => '$$',
        'description' => 'Restaurant indien authentique géré par un chef venu d\'Inde. Épices et saveurs indiennes traditionnelles au Park Mall.',
    ],
    [
        'nom' => 'Keyf-i Mangal',
        'ville' => 'Sétif',
        'wilaya' => 'Sétif',
        'adresse' => 'Park Mall, Sétif 19000',
        'type_cuisine' => 'Turc',
        'gps_latitude' => 36.1937,
        'gps_longitude' => 5.4138,
        'phone' => '+213 36 55 12 34',
        'note_moyenne' => 4.30,
        'price_range' => '$$',
        'description' => 'Restaurant turc au Park Mall servant kebabs, pide, lahmacun et baklava dans une ambiance orientale authentique.',
    ],
    [
        'nom' => 'Serail Restaurant & Lounge',
        'ville' => 'Sétif',
        'wilaya' => 'Sétif',
        'adresse' => '20 Rue Rais Moussa, Sétif 19000',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 36.1905,
        'gps_longitude' => 5.4095,
        'phone' => '+213 36 84 56 78',
        'note_moyenne' => 4.20,
        'price_range' => '$$$',
        'description' => 'Restaurant et lounge avec cuisine variée et ambiance décontractée. Plats algériens et internationaux dans un cadre raffiné.',
    ],
    [
        'nom' => 'LA BRAZA',
        'ville' => 'Sétif',
        'wilaya' => 'Sétif',
        'adresse' => '16 Rue Hanniche Ammar, Sétif 19000',
        'type_cuisine' => 'Grillades',
        'gps_latitude' => 36.1881,
        'gps_longitude' => 5.4062,
        'phone' => '+213 558 602 390',
        'note_moyenne' => 4.00,
        'price_range' => '$$',
        'description' => 'Spécialiste des grillades et viandes braisées. Ambiance chaleureuse et portions généreuses au cœur de Sétif.',
    ],
    [
        'nom' => 'Manola Chicken',
        'ville' => 'Sétif',
        'wilaya' => 'Sétif',
        'adresse' => 'Park Mall, Sétif 19000',
        'type_cuisine' => 'Fast food',
        'gps_latitude' => 36.1935,
        'gps_longitude' => 5.4140,
        'phone' => '+213 36 55 67 89',
        'note_moyenne' => 3.80,
        'price_range' => '$',
        'description' => 'Restaurant de poulet au Park Mall proposant des plats de volaille savoureux et croustillants.',
    ],
    [
        'nom' => 'Restaurant Cheikh Aissa',
        'ville' => 'Sétif',
        'wilaya' => 'Sétif',
        'adresse' => 'Rue Mohamed Fartas, Sétif 19000',
        'type_cuisine' => 'Traditionnel',
        'gps_latitude' => 36.1887,
        'gps_longitude' => 5.4101,
        'phone' => '+213 36 92 45 67',
        'note_moyenne' => 4.10,
        'price_range' => '$',
        'description' => 'Restaurant traditionnel sétifien avec chekhchoukha, couscous, chorba et plats de la cuisine populaire algérienne.',
    ],
    [
        'nom' => 'La Chaumière Club',
        'ville' => 'Sétif',
        'wilaya' => 'Sétif',
        'adresse' => 'Sortie Nord, Sétif 19000',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 36.2010,
        'gps_longitude' => 5.4075,
        'phone' => '+213 36 84 90 12',
        'note_moyenne' => 3.90,
        'price_range' => '$$$',
        'description' => 'Restaurant-club à la sortie nord de Sétif. Cuisine occidentale et algérienne dans un cadre verdoyant et décontracté.',
    ],
    [
        'nom' => 'Bab El Hara',
        'ville' => 'Sétif',
        'wilaya' => 'Sétif',
        'adresse' => 'Rue Meriem Bouatoura, Sétif 19000',
        'type_cuisine' => 'Traditionnel',
        'gps_latitude' => 36.1890,
        'gps_longitude' => 5.4082,
        'phone' => '+213 36 54 33 44',
        'note_moyenne' => 4.00,
        'price_range' => '$',
        'description' => 'Restaurant populaire de cuisine traditionnelle syrienne et algérienne. Plats copieux à prix abordables.',
    ],

    // =========================================================================
    // BEJAIA (Wilaya 06)
    // =========================================================================
    [
        'nom' => 'Restaurant La Citadelle',
        'ville' => 'Béjaïa',
        'wilaya' => 'Béjaïa',
        'adresse' => 'Cité Tobbal, Béjaïa 06000',
        'type_cuisine' => 'Poissons/Fruits de mer',
        'gps_latitude' => 36.7509,
        'gps_longitude' => 5.0567,
        'phone' => '0553 90 54 01',
        'note_moyenne' => 4.80,
        'price_range' => '$$$',
        'description' => 'Classé n°1 des restaurants de Béjaïa. Spécialités de poissons et fruits de mer frais avec cuisine française raffinée.',
    ],
    [
        'nom' => 'Restaurant Le Rima',
        'ville' => 'Béjaïa',
        'wilaya' => 'Béjaïa',
        'adresse' => 'Vieille Ville, près de la Place de la Mairie, Béjaïa 06000',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 36.7555,
        'gps_longitude' => 5.0842,
        'phone' => '+213 34 21 45 67',
        'note_moyenne' => 4.20,
        'price_range' => '$$',
        'description' => 'Restaurant familial dans la vieille ville avec vue sur le port. Cuisine algérienne traditionnelle, service chaleureux et prix modérés.',
    ],
    [
        'nom' => 'O\'Feeling',
        'ville' => 'Béjaïa',
        'wilaya' => 'Béjaïa',
        'adresse' => 'Centre-ville, Béjaïa 06000',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 36.7518,
        'gps_longitude' => 5.0648,
        'phone' => '+213 34 22 78 90',
        'note_moyenne' => 4.30,
        'price_range' => '$$',
        'description' => 'Cuisine algérienne authentique dans une ambiance conviviale. Menu varié mettant en valeur les saveurs kabyles et méditerranéennes.',
    ],
    [
        'nom' => 'Salvador',
        'ville' => 'Béjaïa',
        'wilaya' => 'Béjaïa',
        'adresse' => 'Béjaïa 06000',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 36.7530,
        'gps_longitude' => 5.0700,
        'phone' => '034 106 790',
        'note_moyenne' => 4.00,
        'price_range' => '$$',
        'description' => 'Restaurant proposant une cuisine algérienne variée dans un cadre agréable. Spécialités de la région avec produits locaux.',
    ],
    [
        'nom' => 'Le Self Béjaïa',
        'ville' => 'Béjaïa',
        'wilaya' => 'Béjaïa',
        'adresse' => 'Boulevard des Frères Tikharoubine, Béjaïa 06000',
        'type_cuisine' => 'Café-Restaurant',
        'gps_latitude' => 36.7545,
        'gps_longitude' => 5.0752,
        'phone' => '+213 34 21 56 78',
        'note_moyenne' => 3.80,
        'price_range' => '$',
        'description' => 'Café-restaurant moderne sur le boulevard principal. Plats rapides, sandwiches et boissons dans un cadre décontracté.',
    ],
    [
        'nom' => 'Béjaïa Monte Carlo',
        'ville' => 'Béjaïa',
        'wilaya' => 'Béjaïa',
        'adresse' => 'Boulevard Front de Mer, Béjaïa 06000',
        'type_cuisine' => 'Poissons/Fruits de mer',
        'gps_latitude' => 36.7562,
        'gps_longitude' => 5.0830,
        'phone' => '+213 34 21 90 12',
        'note_moyenne' => 4.10,
        'price_range' => '$$',
        'description' => 'Restaurant de fruits de mer avec terrasse face à la Méditerranée. Poissons grillés et spécialités bougiotes.',
    ],
    [
        'nom' => 'Food Express Akbou',
        'ville' => 'Béjaïa',
        'wilaya' => 'Béjaïa',
        'adresse' => 'Rue Si Larbi Touati, Akbou 06200',
        'type_cuisine' => 'Fast food',
        'gps_latitude' => 36.4615,
        'gps_longitude' => 4.5337,
        'phone' => '+213 780 942 328',
        'note_moyenne' => 3.70,
        'price_range' => '$',
        'description' => 'Fast food à Akbou proposant burgers, tacos et plats rapides à prix accessibles.',
    ],
    [
        'nom' => 'Auberge du Palmier',
        'ville' => 'Béjaïa',
        'wilaya' => 'Béjaïa',
        'adresse' => 'Route de Tichy, Béjaïa 06000',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 36.7399,
        'gps_longitude' => 5.0950,
        'phone' => '+213 34 23 45 67',
        'note_moyenne' => 4.10,
        'price_range' => '$$',
        'description' => 'Auberge-restaurant proposant une cuisine française et algérienne dans un cadre verdoyant à la sortie de Béjaïa.',
    ],
    [
        'nom' => 'Jazz Café Béjaïa',
        'ville' => 'Béjaïa',
        'wilaya' => 'Béjaïa',
        'adresse' => 'Nassim El Bahr, Béjaïa 06000',
        'type_cuisine' => 'Café-Restaurant',
        'gps_latitude' => 36.7540,
        'gps_longitude' => 5.0780,
        'phone' => '+213 34 22 11 22',
        'note_moyenne' => 3.90,
        'price_range' => '$',
        'description' => 'Café-restaurant avec ambiance musicale face à la brise marine. Boissons, pâtisseries et plats légers.',
    ],
    [
        'nom' => 'Brise de Mer',
        'ville' => 'Béjaïa',
        'wilaya' => 'Béjaïa',
        'adresse' => 'Front de Mer, Béjaïa 06000',
        'type_cuisine' => 'Poissons/Fruits de mer',
        'gps_latitude' => 36.7558,
        'gps_longitude' => 5.0825,
        'phone' => '+213 34 21 33 44',
        'note_moyenne' => 4.20,
        'price_range' => '$$',
        'description' => 'Restaurant de poissons en bord de mer à Béjaïa. Poissons grillés, crevettes et calamars frais pêchés du jour.',
    ],

    // =========================================================================
    // TLEMCEN (Wilaya 13)
    // =========================================================================
    [
        'nom' => 'Restaurant l\'Equinoxe',
        'ville' => 'Tlemcen',
        'wilaya' => 'Tlemcen',
        'adresse' => 'Face à l\'Hôpital, Bab El Khemis, Tlemcen 13000',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 34.8828,
        'gps_longitude' => -1.3145,
        'phone' => '+213 43 27 45 67',
        'note_moyenne' => 3.90,
        'price_range' => '$$$',
        'description' => 'Restaurant gastronomique de référence à Tlemcen avec salle et grand patio. Plats modernes teintés de recettes traditionnelles maghrébines.',
    ],
    [
        'nom' => 'L\'Échappatoire',
        'ville' => 'Tlemcen',
        'wilaya' => 'Tlemcen',
        'adresse' => 'Centre-ville, Tlemcen 13000',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 34.8789,
        'gps_longitude' => -1.3150,
        'phone' => '+213 43 20 56 78',
        'note_moyenne' => 3.90,
        'price_range' => '$$',
        'description' => 'Saveurs méditerranéennes où la tradition rencontre l\'art culinaire moderne. Ambiance décontractée et cuisine créative.',
    ],
    [
        'nom' => 'Restaurant Seb\'s Garden',
        'ville' => 'Tlemcen',
        'wilaya' => 'Tlemcen',
        'adresse' => 'Kiffane, Tlemcen 13000',
        'type_cuisine' => 'Traditionnel',
        'gps_latitude' => 34.8850,
        'gps_longitude' => -1.3100,
        'phone' => '+213 43 27 89 01',
        'note_moyenne' => 4.20,
        'price_range' => '$$',
        'description' => 'Cuisine algérienne authentique dans un cadre de jardin tranquille. Spécialités tlemcéniennes et plats du terroir.',
    ],
    [
        'nom' => 'Pizzeria Felicita',
        'ville' => 'Tlemcen',
        'wilaya' => 'Tlemcen',
        'adresse' => 'Centre-ville, Tlemcen 13000',
        'type_cuisine' => 'Pizzeria',
        'gps_latitude' => 34.8795,
        'gps_longitude' => -1.3148,
        'phone' => '+213 43 21 34 56',
        'note_moyenne' => 4.00,
        'price_range' => '$',
        'description' => 'Pizzeria au cœur de Tlemcen avec pizzas traditionnelles cuites au four à bois, ingrédients frais et pâte maison.',
    ],
    [
        'nom' => 'Le Gourmet',
        'ville' => 'Tlemcen',
        'wilaya' => 'Tlemcen',
        'adresse' => '10 Rue Mohamed Abdellaoui, Tlemcen 13000',
        'type_cuisine' => 'Café-Restaurant',
        'gps_latitude' => 34.8810,
        'gps_longitude' => -1.3152,
        'phone' => '+213 661 445 913',
        'note_moyenne' => 3.80,
        'price_range' => '$$',
        'description' => 'Café-restaurant proposant pâtisseries, plats légers et boissons dans un cadre moderne au centre de Tlemcen.',
    ],
    [
        'nom' => 'El Karam',
        'ville' => 'Tlemcen',
        'wilaya' => 'Tlemcen',
        'adresse' => 'Boulevard du 18 Février, Tlemcen 13000',
        'type_cuisine' => 'Grillades',
        'gps_latitude' => 34.8780,
        'gps_longitude' => -1.3140,
        'phone' => '043 21 12 12',
        'note_moyenne' => 4.00,
        'price_range' => '$$',
        'description' => 'Restaurant de grillades réputé sur le boulevard principal. Brochettes, mechoui et viandes grillées au charbon.',
    ],
    [
        'nom' => 'Restaurant El Nasr',
        'ville' => 'Tlemcen',
        'wilaya' => 'Tlemcen',
        'adresse' => 'Rue Houari Boumediene, Tlemcen 13000',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 34.8815,
        'gps_longitude' => -1.3170,
        'phone' => '+213 43 20 78 90',
        'note_moyenne' => 3.80,
        'price_range' => '$',
        'description' => 'Cuisine algérienne authentique avec spécialités tlemcéniennes. Restaurant familial populaire et prix accessibles.',
    ],
    [
        'nom' => 'Al Firdaous',
        'ville' => 'Tlemcen',
        'wilaya' => 'Tlemcen',
        'adresse' => 'Boulevard Allem Mouloud, Tlemcen 13000',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 34.8802,
        'gps_longitude' => -1.3158,
        'phone' => '+213 43 20 45 67',
        'note_moyenne' => 3.90,
        'price_range' => '$$',
        'description' => 'Restaurant algérien avec cuisine généreuse et ambiance conviviale. Tajines, couscous et plats du jour.',
    ],
    [
        'nom' => 'Cyno Fast Food',
        'ville' => 'Tlemcen',
        'wilaya' => 'Tlemcen',
        'adresse' => 'Boulevard de la Soummam, Tlemcen 13000',
        'type_cuisine' => 'Fast food',
        'gps_latitude' => 34.8770,
        'gps_longitude' => -1.3165,
        'phone' => '0556 47 23 44',
        'note_moyenne' => 3.70,
        'price_range' => '$',
        'description' => 'Fast food populaire à Tlemcen proposant burgers, sandwiches et wraps avec un service rapide.',
    ],
    [
        'nom' => 'Restaurant Pizza Ajoued',
        'ville' => 'Tlemcen',
        'wilaya' => 'Tlemcen',
        'adresse' => 'Rue du 5 Juillet, Bab El Assa, Tlemcen 13000',
        'type_cuisine' => 'Pizzeria',
        'gps_latitude' => 34.8835,
        'gps_longitude' => -1.3180,
        'phone' => '+213 675 609 455',
        'note_moyenne' => 3.90,
        'price_range' => '$',
        'description' => 'Pizzeria artisanale à Bab El Assa. Pizzas variées avec pâte fraîche et ingrédients de qualité.',
    ],

    // =========================================================================
    // TIZI OUZOU (Wilaya 15)
    // =========================================================================
    [
        'nom' => 'L\'Ambassade',
        'ville' => 'Tizi Ouzou',
        'wilaya' => 'Tizi Ouzou',
        'adresse' => '14 Rue Douar Mohammed, Tizi Ouzou 15000',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 36.7117,
        'gps_longitude' => 4.0453,
        'phone' => '+213 555 004 173',
        'note_moyenne' => 4.70,
        'price_range' => '$$',
        'description' => 'Restaurant n°1 de Tizi Ouzou. Cuisine algérienne authentique avec couscous le mercredi. Cadre élégant et service impeccable.',
    ],
    [
        'nom' => 'Le Mystic',
        'ville' => 'Tizi Ouzou',
        'wilaya' => 'Tizi Ouzou',
        'adresse' => 'Centre-ville, Tizi Ouzou 15000',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 36.7125,
        'gps_longitude' => 4.0460,
        'phone' => '+213 26 34 56 78',
        'note_moyenne' => 4.00,
        'price_range' => '$$',
        'description' => 'Restaurant chic au décor kabyle et jazz. Cuisine algérienne authentique avec saveurs locales et hospitalité chaleureuse.',
    ],
    [
        'nom' => 'L\'Atelier en Ville',
        'ville' => 'Tizi Ouzou',
        'wilaya' => 'Tizi Ouzou',
        'adresse' => 'Centre-ville, Tizi Ouzou 15000',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 36.7130,
        'gps_longitude' => 4.0470,
        'phone' => '+213 26 34 12 34',
        'note_moyenne' => 4.20,
        'price_range' => '$$',
        'description' => 'Espace chaleureux et spacieux mêlant saveurs locales et cuisine internationale. Équipe accueillante et service rapide.',
    ],
    [
        'nom' => 'Maison Sadoudi',
        'ville' => 'Tizi Ouzou',
        'wilaya' => 'Tizi Ouzou',
        'adresse' => 'Centre-ville, Tizi Ouzou 15000',
        'type_cuisine' => 'Pâtisserie',
        'gps_latitude' => 36.7110,
        'gps_longitude' => 4.0445,
        'phone' => '+213 26 34 78 90',
        'note_moyenne' => 4.60,
        'price_range' => '$$',
        'description' => 'Restaurant gastronomique et pâtisserie réputée. Cuisine traditionnelle kabyle et pâtisseries savoureuses. Service fabuleux.',
    ],
    [
        'nom' => 'Chachnaq',
        'ville' => 'Tizi Ouzou',
        'wilaya' => 'Tizi Ouzou',
        'adresse' => 'Tizi Ouzou 15000',
        'type_cuisine' => 'Traditionnel',
        'gps_latitude' => 36.7115,
        'gps_longitude' => 4.0440,
        'phone' => '+213 26 34 90 12',
        'note_moyenne' => 4.10,
        'price_range' => '$$',
        'description' => 'Restaurant incontournable pour les amateurs de cuisine algérienne authentique à Tizi Ouzou. Plats kabyles traditionnels.',
    ],
    [
        'nom' => 'Restaurant Djaballah',
        'ville' => 'Tizi Ouzou',
        'wilaya' => 'Tizi Ouzou',
        'adresse' => 'Boulevard Zaidat Ahmed, Tizi Ouzou 15300',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 36.7070,
        'gps_longitude' => 4.0505,
        'phone' => '026 34 51 50',
        'note_moyenne' => 3.90,
        'price_range' => '$$',
        'description' => 'Restaurant algérien sur le boulevard Zaidat Ahmed. Plats copieux, couscous et viandes grillées du samedi au jeudi.',
    ],
    [
        'nom' => 'Le Légendaire',
        'ville' => 'Tizi Ouzou',
        'wilaya' => 'Tizi Ouzou',
        'adresse' => 'Route Nationale 12, Tizi Ouzou 15000',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 36.7060,
        'gps_longitude' => 4.0380,
        'phone' => '+213 661 358 323',
        'note_moyenne' => 4.00,
        'price_range' => '$$',
        'description' => 'Restaurant sur la RN12 offrant une cuisine algérienne généreuse. Cadre agréable et plats traditionnels kabyles.',
    ],
    [
        'nom' => 'Restaurant Akfadou',
        'ville' => 'Tizi Ouzou',
        'wilaya' => 'Tizi Ouzou',
        'adresse' => 'Route Nationale 12, Tizi Ouzou 15000',
        'type_cuisine' => 'Traditionnel',
        'gps_latitude' => 36.7065,
        'gps_longitude' => 4.0390,
        'phone' => '+213 663 085 982',
        'note_moyenne' => 3.80,
        'price_range' => '$',
        'description' => 'Cuisine kabyle traditionnelle avec produits locaux. Couscous, tajine de légumes et galettes berbères.',
    ],
    [
        'nom' => 'Restaurant de la Kabylie',
        'ville' => 'Tizi Ouzou',
        'wilaya' => 'Tizi Ouzou',
        'adresse' => 'CW 37, Ait Aissa Mimoun, Tizi Ouzou 15640',
        'type_cuisine' => 'Traditionnel',
        'gps_latitude' => 36.6630,
        'gps_longitude' => 4.1320,
        'phone' => '+213 26 37 45 67',
        'note_moyenne' => 4.00,
        'price_range' => '$',
        'description' => 'Restaurant de terroir au cœur de la Kabylie. Produits locaux, huile d\'olive, couscous kabyle et spécialités montagnardes.',
    ],
    [
        'nom' => 'Hermès Lounge Café',
        'ville' => 'Tizi Ouzou',
        'wilaya' => 'Tizi Ouzou',
        'adresse' => 'Rue des Frères Ouchene, Tizi Ouzou 15000',
        'type_cuisine' => 'Café-Restaurant',
        'gps_latitude' => 36.7120,
        'gps_longitude' => 4.0465,
        'phone' => '+213 26 34 55 66',
        'note_moyenne' => 3.80,
        'price_range' => '$$',
        'description' => 'Lounge café élégant avec pâtisseries, boissons chaudes et plats légers dans une ambiance tendance.',
    ],

    // =========================================================================
    // BISKRA (Wilaya 07)
    // =========================================================================
    [
        'nom' => 'Tanjra Restaurant',
        'ville' => 'Biskra',
        'wilaya' => 'Biskra',
        'adresse' => 'Route Nationale, entre Biskra et Ouargla, Biskra 07000',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 34.8400,
        'gps_longitude' => 5.7300,
        'phone' => '+213 33 74 56 78',
        'note_moyenne' => 4.70,
        'price_range' => '$$',
        'description' => 'Restaurant familial spacieux avec architecture magnifique, entouré d\'une ferme. Nourriture délicieuse et parking gratuit.',
    ],
    [
        'nom' => 'El Nour Restaurant',
        'ville' => 'Biskra',
        'wilaya' => 'Biskra',
        'adresse' => 'Centre-ville, Biskra 07000',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 34.8490,
        'gps_longitude' => 5.7280,
        'phone' => '+213 33 74 12 34',
        'note_moyenne' => 5.00,
        'price_range' => '$$',
        'description' => 'Cuisine arabe et algérienne au centre de Biskra. Réputé pour ses plats authentiques du Sud et ses grillades.',
    ],
    [
        'nom' => 'Restaurant Janitou',
        'ville' => 'Biskra',
        'wilaya' => 'Biskra',
        'adresse' => 'Centre-ville, Biskra 07000',
        'type_cuisine' => 'Traditionnel',
        'gps_latitude' => 34.8470,
        'gps_longitude' => 5.7260,
        'phone' => '+213 33 74 45 67',
        'note_moyenne' => 4.30,
        'price_range' => '$$',
        'description' => 'Restaurant traditionnel proposant des plats du Sud algérien dont la chekhchoukha biskrie et le couscous au mouton.',
    ],
    [
        'nom' => 'Hôtel Restaurant Selami',
        'ville' => 'Biskra',
        'wilaya' => 'Biskra',
        'adresse' => 'Près du centre-ville, Biskra 07000',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 34.8460,
        'gps_longitude' => 5.7270,
        'phone' => '+213 33 74 67 89',
        'note_moyenne' => 3.80,
        'price_range' => '$$',
        'description' => 'Restaurant d\'hôtel au centre de Biskra. Cuisine algérienne et internationale dans un cadre confortable.',
    ],
    [
        'nom' => 'Sami Food',
        'ville' => 'Biskra',
        'wilaya' => 'Biskra',
        'adresse' => 'Allées Mohamed Seddik Ben Yahia, Biskra 07000',
        'type_cuisine' => 'Fast food',
        'gps_latitude' => 34.8506,
        'gps_longitude' => 5.7064,
        'phone' => '+213 33 74 23 45',
        'note_moyenne' => 3.70,
        'price_range' => '$',
        'description' => 'Restaurant rapide près de la mairie et du marché Souk El Rahma. Sandwiches, grillades et plats du jour.',
    ],
    [
        'nom' => 'Restaurant El Widad',
        'ville' => 'Biskra',
        'wilaya' => 'Biskra',
        'adresse' => 'Boulevard Lahloul Mammar, Biskra 07000',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 34.8543,
        'gps_longitude' => 5.7285,
        'phone' => '+213 33 74 34 56',
        'note_moyenne' => 3.90,
        'price_range' => '$$',
        'description' => 'Restaurant algérien près de la Grande Mosquée. Plats traditionnels du Sud, couscous et tajines.',
    ],
    [
        'nom' => 'Doubara ElKhaima',
        'ville' => 'Biskra',
        'wilaya' => 'Biskra',
        'adresse' => 'Boulevard Si El Haouès, Biskra 07000',
        'type_cuisine' => 'Traditionnel',
        'gps_latitude' => 34.8480,
        'gps_longitude' => 5.7240,
        'phone' => '+213 33 74 56 12',
        'note_moyenne' => 4.40,
        'price_range' => '$',
        'description' => 'Spécialiste de la doubara biskrie, plat emblématique de Biskra à base de pois chiches. Cuisine de rue authentique.',
    ],
    [
        'nom' => 'Mokrani Pizza Shop',
        'ville' => 'Biskra',
        'wilaya' => 'Biskra',
        'adresse' => 'Rue Frères Messaoud, Biskra 07000',
        'type_cuisine' => 'Pizzeria',
        'gps_latitude' => 34.8495,
        'gps_longitude' => 5.7250,
        'phone' => '+213 33 74 78 90',
        'note_moyenne' => 3.80,
        'price_range' => '$',
        'description' => 'Pizzeria de quartier à Biskra avec pizzas généreuses et variées. Prix abordables et service rapide.',
    ],
    [
        'nom' => 'Mr. BBQ Biskra',
        'ville' => 'Biskra',
        'wilaya' => 'Biskra',
        'adresse' => 'Centre-ville, Biskra 07000',
        'type_cuisine' => 'Grillades',
        'gps_latitude' => 34.8485,
        'gps_longitude' => 5.7268,
        'phone' => '+213 661 51 98 92',
        'note_moyenne' => 4.00,
        'price_range' => '$$',
        'description' => 'Spécialiste des grillades et barbecue. Brochettes, côtelettes et viandes marinées au charbon de bois.',
    ],
    [
        'nom' => 'Le Cordon Bleu',
        'ville' => 'Biskra',
        'wilaya' => 'Biskra',
        'adresse' => 'Rue principale, Biskra 07000',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 34.8500,
        'gps_longitude' => 5.7275,
        'phone' => '+213 33 74 89 01',
        'note_moyenne' => 3.70,
        'price_range' => '$$',
        'description' => 'Restaurant proposant une cuisine algérienne variée avec des touches françaises. Cadre agréable au centre de Biskra.',
    ],

    // =========================================================================
    // GHARDAIA (Wilaya 47)
    // =========================================================================
    [
        'nom' => 'Restaurant Le Palmier',
        'ville' => 'Ghardaïa',
        'wilaya' => 'Ghardaïa',
        'adresse' => 'Centre-ville, Ghardaïa 47000',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 32.4912,
        'gps_longitude' => 3.6734,
        'phone' => '+213 29 88 34 56',
        'note_moyenne' => 4.30,
        'price_range' => '$$$',
        'description' => 'Meilleur restaurant établi de Ghardaïa selon Lonely Planet. Salle chic avec arts traditionnels, menu trois services et carte européenne/algérienne.',
    ],
    [
        'nom' => 'L\'Escale Street Food',
        'ville' => 'Ghardaïa',
        'wilaya' => 'Ghardaïa',
        'adresse' => 'Avenue du 1er Novembre, Ghardaïa 47000',
        'type_cuisine' => 'Pizzeria',
        'gps_latitude' => 32.4900,
        'gps_longitude' => 3.6720,
        'phone' => '+213 29 88 12 34',
        'note_moyenne' => 3.80,
        'price_range' => '$',
        'description' => 'Pizzas, pâtes, pommes de terre et autres spécialités rapides avec saveurs arabes et italiennes au cœur de Ghardaïa.',
    ],
    [
        'nom' => 'Eldjawhara Hotel Restaurant',
        'ville' => 'Ghardaïa',
        'wilaya' => 'Ghardaïa',
        'adresse' => 'Centre-ville, Ghardaïa 47000',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 32.4920,
        'gps_longitude' => 3.6745,
        'phone' => '+213 29 88 56 78',
        'note_moyenne' => 3.00,
        'price_range' => '$$',
        'description' => 'Restaurant d\'hôtel proposant une cuisine algérienne traditionnelle dans un cadre confortable avec vue sur la vallée du M\'zab.',
    ],
    [
        'nom' => 'Restaurant Djurdjura',
        'ville' => 'Ghardaïa',
        'wilaya' => 'Ghardaïa',
        'adresse' => 'Sidi Abaz N°1, Bounoura, Ghardaïa 47100',
        'type_cuisine' => 'Traditionnel',
        'gps_latitude' => 32.5050,
        'gps_longitude' => 3.6680,
        'phone' => '+213 29 88 78 90',
        'note_moyenne' => 3.80,
        'price_range' => '$',
        'description' => 'Restaurant de cuisine locale mozabite à Bounoura. Plats traditionnels servis sur place uniquement.',
    ],
    [
        'nom' => 'Restaurant Tiliwine',
        'ville' => 'Ghardaïa',
        'wilaya' => 'Ghardaïa',
        'adresse' => 'Bounoura, Ghardaïa 47100',
        'type_cuisine' => 'Traditionnel',
        'gps_latitude' => 32.5060,
        'gps_longitude' => 3.6690,
        'phone' => '+213 29 88 90 12',
        'note_moyenne' => 3.90,
        'price_range' => '$',
        'description' => 'Restaurant de spécialités mozabites traditionnelles à Bounoura. Cuisine du terroir avec produits locaux du M\'zab.',
    ],
    [
        'nom' => 'M\'zab Restaurant',
        'ville' => 'Ghardaïa',
        'wilaya' => 'Ghardaïa',
        'adresse' => 'Centre-ville, Ghardaïa 47000',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 32.4895,
        'gps_longitude' => 3.6710,
        'phone' => '+213 29 88 23 45',
        'note_moyenne' => 2.00,
        'price_range' => '$',
        'description' => 'Restaurant algérien au centre de Ghardaïa proposant couscous, tajines et plats sahariens.',
    ],
    [
        'nom' => 'Restaurant El Zaim',
        'ville' => 'Ghardaïa',
        'wilaya' => 'Ghardaïa',
        'adresse' => 'Avenue de l\'ALN, Ghardaïa 47000',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 32.4915,
        'gps_longitude' => 3.6738,
        'phone' => '+213 550 474 716',
        'note_moyenne' => 3.70,
        'price_range' => '$',
        'description' => 'Restaurant populaire sur l\'avenue de l\'ALN. Cuisine algérienne copieuse et accueil chaleureux saharien.',
    ],
    [
        'nom' => 'Cafétéria Elgosto',
        'ville' => 'Ghardaïa',
        'wilaya' => 'Ghardaïa',
        'adresse' => 'Avenue Ahmed Talbi, Ghardaïa 47000',
        'type_cuisine' => 'Café-Restaurant',
        'gps_latitude' => 32.4908,
        'gps_longitude' => 3.6730,
        'phone' => '+213 772 009 191',
        'note_moyenne' => 3.60,
        'price_range' => '$',
        'description' => 'Cafétéria moderne proposant boissons, snacks et plats légers. Point de rencontre populaire à Ghardaïa.',
    ],
    [
        'nom' => 'MC Daddy',
        'ville' => 'Ghardaïa',
        'wilaya' => 'Ghardaïa',
        'adresse' => 'Centre-ville, Ghardaïa 47000',
        'type_cuisine' => 'Fast food',
        'gps_latitude' => 32.4905,
        'gps_longitude' => 3.6725,
        'phone' => '+213 29 88 45 67',
        'note_moyenne' => 3.50,
        'price_range' => '$',
        'description' => 'Fast food casual proposant burgers, frites et sandwiches dans un cadre décontracté.',
    ],
    [
        'nom' => 'Marina Burger',
        'ville' => 'Ghardaïa',
        'wilaya' => 'Ghardaïa',
        'adresse' => 'Centre-ville, Ghardaïa 47000',
        'type_cuisine' => 'Fast food',
        'gps_latitude' => 32.4910,
        'gps_longitude' => 3.6742,
        'phone' => '+213 29 88 67 89',
        'note_moyenne' => 3.40,
        'price_range' => '$',
        'description' => 'Spécialiste du burger à Ghardaïa. Burgers artisanaux, frites maison et boissons fraîches.',
    ],

    // =========================================================================
    // TIPAZA (Wilaya 42)
    // =========================================================================
    [
        'nom' => 'Le Dauphin - Chez Sid Ali',
        'ville' => 'Tipaza',
        'wilaya' => 'Tipaza',
        'adresse' => 'Rue du Port, Tipaza 42000',
        'type_cuisine' => 'Poissons/Fruits de mer',
        'gps_latitude' => 36.5931,
        'gps_longitude' => 2.4502,
        'phone' => '024 37 06 58',
        'note_moyenne' => 4.20,
        'price_range' => '$$',
        'description' => 'Meilleure adresse de Tipaza pour le poisson frais grillé. Saumon au charbon, crevettes frites et vue apaisante sur le port.',
    ],
    [
        'nom' => 'Restaurant Albert Camus',
        'ville' => 'Tipaza',
        'wilaya' => 'Tipaza',
        'adresse' => 'Port de Tipaza, Tipaza 42000',
        'type_cuisine' => 'Poissons/Fruits de mer',
        'gps_latitude' => 36.5925,
        'gps_longitude' => 2.4498,
        'phone' => '024 37 06 13',
        'note_moyenne' => 4.00,
        'price_range' => '$$$',
        'description' => 'Restaurant gastronomique au cœur du port spécialisé en poissons et paella. Cuisine méditerranéenne raffinée.',
    ],
    [
        'nom' => 'Restaurant Les Oursins',
        'ville' => 'Tipaza',
        'wilaya' => 'Tipaza',
        'adresse' => 'Ain Tagourait, Tipaza 42000',
        'type_cuisine' => 'Poissons/Fruits de mer',
        'gps_latitude' => 36.5880,
        'gps_longitude' => 2.4450,
        'phone' => '+213 24 37 45 67',
        'note_moyenne' => 4.20,
        'price_range' => '$$',
        'description' => 'Restaurant méditerranéen de fruits de mer à Ain Tagourait. Oursins, crevettes et poissons grillés face à la mer.',
    ],
    [
        'nom' => 'Casa Mia Poissonerie',
        'ville' => 'Tipaza',
        'wilaya' => 'Tipaza',
        'adresse' => 'Rue du Port, Tipaza 42000',
        'type_cuisine' => 'Poissons/Fruits de mer',
        'gps_latitude' => 36.5930,
        'gps_longitude' => 2.4497,
        'phone' => '+213 24 37 78 90',
        'note_moyenne' => 4.10,
        'price_range' => '$$',
        'description' => 'Poissonnerie-restaurant près du port et du musée archéologique. Poissons ultra-frais cuisinés sur place.',
    ],
    [
        'nom' => 'El Kahina',
        'ville' => 'Tipaza',
        'wilaya' => 'Tipaza',
        'adresse' => 'Corniche, Tipaza 42000',
        'type_cuisine' => 'Poissons/Fruits de mer',
        'gps_latitude' => 36.5940,
        'gps_longitude' => 2.4510,
        'phone' => '+213 24 37 12 34',
        'note_moyenne' => 4.20,
        'price_range' => '$$',
        'description' => 'Restaurant de fruits de mer sur la corniche de Tipaza. Poissons grillés et bouillabaisse avec vue sur la Méditerranée.',
    ],
    [
        'nom' => 'Le Poseidon',
        'ville' => 'Tipaza',
        'wilaya' => 'Tipaza',
        'adresse' => 'Bord de mer, Tipaza 42000',
        'type_cuisine' => 'Poissons/Fruits de mer',
        'gps_latitude' => 36.5935,
        'gps_longitude' => 2.4505,
        'phone' => '+213 24 37 56 78',
        'note_moyenne' => 4.00,
        'price_range' => '$$',
        'description' => 'Restaurant de poissons en bord de mer. Fruits de mer frais et grillades dans un cadre maritime authentique.',
    ],
    [
        'nom' => 'Restaurant Chez Sauveur',
        'ville' => 'Tipaza',
        'wilaya' => 'Tipaza',
        'adresse' => 'Centre-ville, Tipaza 42000',
        'type_cuisine' => 'Poissons/Fruits de mer',
        'gps_latitude' => 36.5920,
        'gps_longitude' => 2.4490,
        'phone' => '+213 24 37 34 56',
        'note_moyenne' => 3.60,
        'price_range' => '$$',
        'description' => 'Restaurant traditionnel de poissons avec une longue histoire à Tipaza. Cuisine de la mer simple et authentique.',
    ],
    [
        'nom' => 'Le Romana',
        'ville' => 'Tipaza',
        'wilaya' => 'Tipaza',
        'adresse' => 'Rue Aïssat Idir, Tipaza 42000',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 36.5918,
        'gps_longitude' => 2.4480,
        'phone' => '+213 24 37 90 12',
        'note_moyenne' => 3.80,
        'price_range' => '$$',
        'description' => 'Restaurant algérien près des ruines romaines. Cuisine traditionnelle avec terrasse donnant sur le site archéologique.',
    ],
    [
        'nom' => 'Restaurant Liberté',
        'ville' => 'Tipaza',
        'wilaya' => 'Tipaza',
        'adresse' => 'Douaouda Marine, Tipaza 42000',
        'type_cuisine' => 'Poissons/Fruits de mer',
        'gps_latitude' => 36.6640,
        'gps_longitude' => 2.7690,
        'phone' => '+213 24 46 12 34',
        'note_moyenne' => 3.90,
        'price_range' => '$',
        'description' => 'Restaurant de poissons à Douaouda Marine. Poissons frais grillés à petit prix dans un cadre maritime simple.',
    ],
    [
        'nom' => 'Le Perdrix',
        'ville' => 'Tipaza',
        'wilaya' => 'Tipaza',
        'adresse' => 'RN11, Bou Ismaïl, Tipaza 42004',
        'type_cuisine' => 'Algérien',
        'gps_latitude' => 36.6420,
        'gps_longitude' => 2.6880,
        'phone' => '+213 24 46 56 78',
        'note_moyenne' => 3.70,
        'price_range' => '$$',
        'description' => 'Restaurant sur la RN11 à Bou Ismaïl. Cuisine algérienne variée avec viandes grillées et plats traditionnels.',
    ],
];

// =========================================================================
// INSERT RESTAURANTS
// =========================================================================

$insertSql = "INSERT INTO restaurants
    (nom, slug, ville, wilaya, pays, adresse, type_cuisine, gps_latitude, gps_longitude,
     phone, note_moyenne, price_range, description, descriptif, status, verified_halal, created_at)
    VALUES
    (:nom, :slug, :ville, :wilaya, 'Algérie', :adresse, :type_cuisine, :gps_latitude, :gps_longitude,
     :phone, :note_moyenne, :price_range, :description, :descriptif, 'validated', 1, NOW())";

$stmt = $pdo->prepare($insertSql);

$inserted = 0;
$skipped = 0;
$errors = 0;

foreach ($restaurants as $r) {
    $slug = slugify($r['nom'] . '-' . $r['ville']);

    // Check if already exists
    $check = $pdo->prepare("SELECT id FROM restaurants WHERE slug = :slug");
    $check->execute([':slug' => $slug]);
    if ($check->fetchColumn()) {
        echo "SKIP (exists): {$r['nom']} - {$r['ville']}\n";
        $skipped++;
        continue;
    }

    try {
        $descriptif = "Restaurant à {$r['ville']} - Note: {$r['note_moyenne']}/5";
        $stmt->execute([
            ':nom' => $r['nom'],
            ':slug' => $slug,
            ':ville' => $r['ville'],
            ':wilaya' => $r['wilaya'],
            ':adresse' => $r['adresse'],
            ':type_cuisine' => $r['type_cuisine'],
            ':gps_latitude' => $r['gps_latitude'],
            ':gps_longitude' => $r['gps_longitude'],
            ':phone' => $r['phone'],
            ':note_moyenne' => $r['note_moyenne'],
            ':price_range' => $r['price_range'],
            ':description' => $r['description'],
            ':descriptif' => $descriptif,
        ]);
        $inserted++;
        echo "OK: {$r['nom']} ({$r['ville']})\n";
    } catch (PDOException $e) {
        echo "ERR: {$r['nom']} - {$e->getMessage()}\n";
        $errors++;
    }
}

echo "\n========================================\n";
echo "DONE!\n";
echo "Inserted: $inserted\n";
echo "Skipped: $skipped\n";
echo "Errors: $errors\n";
echo "Total in array: " . count($restaurants) . "\n";
echo "========================================\n";

// Show counts per city
$cityStats = $pdo->query("SELECT ville, COUNT(*) as c FROM restaurants WHERE status='validated' GROUP BY ville ORDER BY c DESC")->fetchAll(PDO::FETCH_ASSOC);
echo "\nRestaurants per city:\n";
foreach ($cityStats as $row) {
    echo "  {$row['ville']}: {$row['c']}\n";
}
echo "Total validated: " . $pdo->query("SELECT COUNT(*) FROM restaurants WHERE status='validated'")->fetchColumn() . "\n";
